### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-chirat_deschamps#1]
❓ Le rapport tout en italique c'est voulu ?

⚠️ Il est où l'uml ?

⚠️ C'est bizarre mais certaines implem de vos visteurs se ressemblent ? Il ya surement des méthodes qui pourraient être implémentées à un autre niveau de l'arbre d'héritage.

❓ la priorité de la multiplication ça marche comment  ?

👍 Le reste c'est pas mal

**Comment by LeoDeschamps** [comment]
Nous avons essayé de corriger les problèmes dont vous parlez dans le dernier commit !

Pour ce qui est de la priorité des opérations, nous n'avons pas défini de règles particulières, nous nous disions que ces règles de priorités étaient gérées "automatiquement" avec l'ordre de parcours des nœuds, car nous trouvé le bon résultat pour le calcul de la valeur..

**Comment by Slashgear** [comment]
ça me va 👍
